### ISSUE TITLE
Item.drop flag improvements

### ISSUE THREAD

**Issue by WolFire1** [prism/SafeGuard#15]
So many items are lost to zones when item.drop isn't toggled true. If I drop an item in a zone with item.drop toggled off, the item will be lost forever (except I'm an Op). Perhaps return the item to the player if item.drop is denied, and/or default item.drop to true so that players don't mistakenly have their friends drop items and not get them back.

**Comment by viveleroi** [comment]
This is a sponge bug which I've alerted them to.
